In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn import svm
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [6]:
data=[1,2,3,4,5,6,7,8,9,10,11,12,1,1,2,3,4,5,6,7,8,6,5,4,3,2,1,2,3,4]

In [7]:
len(data)

30

In [8]:

df_numpy = np.asarray(data, dtype = float)
df_numpy

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,
        1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  6.,  5.,  4.,  3.,  2.,
        1.,  2.,  3.,  4.])

In [10]:
df_numpy = df_numpy.reshape(1,30)
df_numpy

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,
         1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  6.,  5.,  4.,  3.,  2.,
         1.,  2.,  3.,  4.]])

In [11]:
df_numpy11 = df_numpy.reshape(1,-1)
df_numpy11

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,
         1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  6.,  5.,  4.,  3.,  2.,
         1.,  2.,  3.,  4.]])

In [16]:
from model import train_svm, test_svm, predict_svm


In [17]:
output, acc= predict_svm(clf, df_numpy)

NameError: name 'clf' is not defined

In [20]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from time import time



data=pd.read_csv("Breast Cancer Data.csv")
df=data.drop("Unnamed: 32",axis=1)
df=data.drop("id",axis=1)

df.drop(columns=["Unnamed: 32"],inplace=True)
X=df.drop(labels="diagnosis",axis=1)
y=df["diagnosis"]
X=X.values
y=y.values

from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
y = labelencoder_X_1.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [21]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = SVC(probability=True)
clf.fit(X_train, y_train)

output = clf.predict(X_test)
acc = accuracy_score(y_test, output)
print("The accuracy of testing data: ",acc)



The accuracy of testing data:  0.9824561403508771


In [22]:
inp = sc.transform(df_numpy)
inp

array([[-3.71302438e+00, -4.12885609e+00, -3.65713842e+00,
        -1.81629206e+00,  3.55739849e+02,  1.16917711e+02,
         8.89458824e+01,  2.06232756e+02,  3.22242510e+02,
         1.45894160e+03,  3.73074521e+01,  1.99313086e+01,
        -8.96700994e-01, -8.23978900e-01,  7.01626652e+02,
         1.70088555e+02,  1.27722117e+02,  8.46816576e+02,
         7.30319089e+02,  2.68384120e+03, -1.69003045e+00,
        -3.20626712e+00, -3.01583011e+00, -1.49754764e+00,
         1.26877370e+02,  1.14301458e+01,  3.67323248e+00,
         2.88977987e+01,  4.30624040e+01,  2.20098483e+02]])

In [23]:
output = clf.predict(inp)
output

array([1])

In [25]:
acc = clf.predict_proba(inp)
acc

array([[0.28883044, 0.71116956]])

In [26]:
if(output==1):
    final_output = 'Malignant'
else:
    final_output = 'Benign'
print(final_output)

Malignant


In [27]:
accuracy_x = acc[0][0]
print(accuracy_x)
accuracy_y = acc[0][1]
print(accuracy_y)


0.28883043996192304
0.711169560038077


In [28]:
if(accuracy_x>accuracy_y):
    acc = accuracy_x
else:
    acc=accuracy_y
print(acc)

0.711169560038077


In [ ]:
return render_template('result.html', output=final_output, accuracy=acc*100)